INSERT INTO DOMAINS (DOMAIN_DESC, DOMAIN_NAME) VALUES ('AAP Admin Description', 'AAPAdmin');
INSERT INTO DOMAINS (DOMAIN_DESC, DOMAIN_NAME) VALUES ('PRIDE Admin Description', 'PRIDEAdmin');
INSERT INTO DOMAINS (DOMAIN_DESC, DOMAIN_NAME) VALUES ('EGA Admin Description', 'EGAAdmin');
INSERT INTO DOMAINS (DOMAIN_DESC, DOMAIN_NAME) VALUES ('PRIDE Submission Description', 'PRIDESubmission');
INSERT INTO DOMAINS (DOMAIN_DESC, DOMAIN_NAME) VALUES ('EGA Submission Description', 'EGASubmission');
INSERT INTO DOMAINS (DOMAIN_DESC, DOMAIN_NAME) VALUES ('PRIDE Reviewers Description', 'PRIDEReviewer');
INSERT INTO DOMAINS (DOMAIN_DESC, DOMAIN_NAME) VALUES ('EGA Reviewers Description', 'EGAReviewer');
INSERT INTO DOMAINS (DOMAIN_DESC, DOMAIN_NAME) VALUES ('EGA Management Description', 'EGAManagement');

INSERT INTO PUBLIC.USERS (USER_NAME, EMAIL) VALUES ('test1', 'test1@test.com');
INSERT INTO PUBLIC.USERS (USER_NAME, EMAIL) VALUES ('test2', 'test2@test.com');
INSERT INTO PUBLIC.USERS (USER_NAME, EMAIL) VALUES ('test3', 'test3@test.com');
INSERT INTO PUBLIC.USERS (USER_NAME, EMAIL) VALUES ('test1', 'test1@test.com');



