DROP TABLE USER_DOMAIN IF EXISTS ;
DROP TABLE USERS IF EXISTS;
DROP TABLE DOMAINS IF EXISTS;


--
-- Table structure for table `domains`
--
CREATE TABLE DOMAINS
(
  ID BIGINT PRIMARY KEY NOT NULL IDENTITY,
  DOMAIN_DESC VARCHAR(255),
  DOMAIN_NAME VARCHAR(255)
);

--
-- Table structure for table `users`
--

CREATE TABLE USERS
(
  ID BIGINT PRIMARY KEY NOT NULL IDENTITY,
  USER_NAME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(200) NOT NULL
);

--CREATE UNIQUE INDEX "users_email_uindex" ON USERS (EMAIL);
--CREATE UNIQUE INDEX "users_user_name_uindex" ON USERS (USER_NAME);


--
-- Table structure for table `USER_DOMAIN`
--


CREATE TABLE USER_DOMAIN (
  domain_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  PRIMARY KEY (domain_id,user_id),
  CONSTRAINT FK_USER_DOMAIN_DOMAINS FOREIGN KEY (domain_id) REFERENCES DOMAINS (ID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_USER_DOMAIN_USERS FOREIGN KEY (user_id) REFERENCES USERS (ID) ON DELETE CASCADE ON UPDATE CASCADE
)







